gnome: Upgrade WebKitGtk to 2.12.3
New version is needed to build with glibc 2.23. Builds were
failing with:

    [ 13%] Building CXX object Source/JavaScriptCore/CMakeFiles/JavaScriptCore.dir/runtime/RegExpCachedResult.cpp.o
    /WebKitGtk.build/Source/JavaScriptCore/runtime/Options.cpp: In member function 'bool JSC::Option::operator==(const JSC::Option&) const':
    /WebKitGtk.build/Source/JavaScriptCore/runtime/Options.cpp:613:90: error: 'isnan' was not declared in this scope
             return (m_entry.doubleVal == other.m_entry.doubleVal) || (isnan(m_entry.doubleVal) && isnan(other.m_entry.doubleVal));
                                                                                              ^
    /WebKitGtk.build/Source/JavaScriptCore/runtime/Options.cpp:613:90: note: suggested alternative:
    In file included from /usr/include/c++/5.3.0/random:38:0,
                     from /usr/include/c++/5.3.0/bits/stl_algo.h:66,
                     from /usr/include/c++/5.3.0/algorithm:62,
                     from /WebKitGtk.build/Source/WTF/wtf/RefPtr.h:26,
                     from /WebKitGtk.build/Source/WTF/wtf/VectorTraits.h:25,
                     from /WebKitGtk.build/Source/WTF/wtf/Vector.h:35,
                     from /WebKitGtk.build/Source/WTF/wtf/Deque.h:37,
                     from /WebKitGtk.build/Source/JavaScriptCore/heap/HeapStatistics.h:30,
                     from /WebKitGtk.build/Source/JavaScriptCore/runtime/Options.cpp:29:
    /usr/include/c++/5.3.0/cmath:641:5: note:   'std::isnan'
         isnan(_Tp __x)
         ^

Change-Id: I0e5111c1d6e0b7f4c6db28e3e7a995ef4706b316